- hosts: all
  tasks:
          - name: "Configuring Docker repo"
            yum_repository:
                     baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
                     name: "docker"
                     description: "docker repo file"
                     gpgcheck: no
                     state: present

          - yum_repository:
                     baseurl: "file:///run/media/root/RHEL-8-0-0-BaseOS-x86_64/AppStream"
                     name: "mydvd1"
                     description: "mydvd1 repository"
                     gpgcheck: no
                     state: present 

          - yum_repository:
                     baseurl: "file:///run/media/root/RHEL-8-0-0-BaseOS-x86_64/BaseOS"
                     name: "mydvd2"
                     description: "mydvd2 repository"
                     gpgcheck: no
                     state: present

          - name: "install docker  -ce"
            package:
                     name: "docker-ce-18.09.1"
                     state: latest

          - name: "Start Docker Service"
            service:
                     name: "docker"
                     state: started

          - name: "Install Docker python Lib" 
            pip:
                     name: "docker-py"
                     state: present
   
          - name: "Pull an image"
            docker_image:
                     name: httpd
                     tag: latest
                     source: pull

          - name: "Copy the page to /var/www/html folder"
            copy:
                     src: "web.html"
                     dest: "/var/www/html"

          - name: "Launch a Docker Container"
            docker_container:
                     name: "ansible_docker"
                     image: httpd
                     states: started
                     ports: "4141:80"
                     exposed_ports: "80"
                     volumes: "/var/www/html/:/user/local/apache2/htdocs"

          - name: "Firewall rule"
            firewalld:
                     port: "4141/tcp"
                     state: enabled
                     permanent: yes
                     immediate: yes
                    


    